name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag netavark-builder:$(date +%s)

    - name: Run temporary image and copy the file
      run: |
        docker run --name temp-container netavark-builder:$(date +%s)
        docker cp temp-container:/usr/local/bin/netavark ./netavark
        docker rm temp-container

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.1
      with:
        path: ./netavark
        name: netavark

#    - name: Upload a Build Artifact
#      uses: actions/upload-artifact@v2.1.1
#      with:
#        path: /usr/local/bin/netavark
#        name: netavark

#    - name: Upload a Build Artifact archive amd64
#      uses: actions/upload-artifact@v2.1.1
#      with:
#        path: ./build/asset/netavark-linux-amd64.tar.gz
#        name: netavark-linux-amd64.tar.gz

#    - name: Upload a Build Artifact signature amd64
#      uses: actions/upload-artifact@v2.1.1
#      with:
#        path: ./build/asset/podman-linux-amd64.tar.gz.asc
#        name: podman-linux-amd64.tar.gz.asc

#    - name: Upload a Build Artifact archive aarch64
#      uses: actions/upload-artifact@v2.1.1
#      with:
#        path: ./build/asset/netavark-linux-arm64.tar.gz
#        name: netavark-linux-arm64.tar.gz

#    - name: Upload a Build Artifact signature aarch64
#      uses: actions/upload-artifact@v2.1.1
#      with:
#        path: ./build/asset/podman-linux-arm64.tar.gz.asc
#        name: podman-linux-arm64.tar.gz.asc
